export default {
  emailLabel: 'Почта',
  emailName: 'email',
  loginLabel: 'Логин',
  loginName: 'login',
  firstNameLabel: 'Имя',
  firstNameName: 'first_name',
  secondNameLabel: 'Фамилия',
  secondNameName: 'second_name',
  phoneLabel: 'Телефон',
  phoneName: 'phone',
  passwordLabel: 'Пароль',
  passwordName: 'password',
  repeatPasswordLabel: 'Пароль (ещё раз)',
  repeatPasswordName: 'repeatPassword',
  regText: 'Зарегистрироваться',
};
