export default {
  emailLabel: 'Почта',
  emailName: 'email',
  loginLabel: 'Логин',
  loginName: 'login',
  firstNameLabel: 'Имя',
  firstNameName: 'first_name',
  secondNameLabel: 'Фамилия',
  secondNameName: 'second_name',
  phoneLabel: 'Телефон',
  phoneName: 'phone',
  oldPasswordLabel: 'Старый пароль',
  oldPasswordName: 'oldPassword',
  passwordLabel: 'Новый пароль',
  passwordName: 'password',
  repeatPasswordLabel: 'Повторите новый пароль',
  repeatPasswordName: 'repeatPassword',
};
